version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-phase}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-phase}
      POSTGRES_DB: ${POSTGRES_DB:-phase}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"

  mailcatcher:
    image: schickling/mailcatcher:latest
    restart: unless-stopped
    ports:
      - "1080:1080"
      - "1025:1025"

volumes:
  postgres-data:
