name: Build Android

on:
  push:
    branches:
      - main
      - develop
      - feat/**
  pull_request:

jobs:
  build-android:
    name: Build Android (APK)
    runs-on: ubuntu-latest
    environment: unity-build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ runner.os }}-${{ hashFiles('**/Packages/manifest.json') }}-${{ hashFiles('**/Packages/packages-lock.json') }}
          restore-keys: |
            Library-${{ runner.os }}-

      - name: Build Android
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_VERSION: 2022.3.16f1
        with:
          targetPlatform: Android
          androidAppBundle: false
          buildName: HollowKnightLike
          buildPath: build/android

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: build/android
