name: Build Android

permissions:
  contents: write

on:
  push:
    branches:
      - main
      - develop
      - feat/**
  pull_request:

jobs:
  build-android:
    name: Build Android (APK)
    runs-on: ubuntu-latest
    environment: unity-build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Cache Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ runner.os }}-${{ hashFiles('**/Packages/manifest.json') }}-${{ hashFiles('**/Packages/packages-lock.json') }}
          restore-keys: |
            Library-${{ runner.os }}-

      - name: Build Android
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_VERSION: 2022.3.16f1
        with:
          targetPlatform: Android
          androidAppBundle: false
          buildName: HollowKnightLike
          buildPath: build/android

      - name: Commit Unity-generated changes (if any)
        run: |
          echo "Checking for changes..."
          if [ -n "$(git status --porcelain)" ]; then
            echo "Found changes — committing back to branch so semantic version can run cleanly."
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "ci: commit ProjectSettings changes generated during CI" || echo "No commit created"
            # Push the commit back to the same ref
            git push
          else
            echo "No changes to commit."
          fi

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/android
