name: Build and deploy WebGL

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: webgl-pages
  cancel-in-progress: false

jobs:
  build:
    name: Build WebGL
    runs-on: ubuntu-latest
    env:
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Library folder
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ runner.os }}-${{ hashFiles('Packages/manifest.json') }}
          restore-keys: |
            Library-${{ runner.os }}-

      - name: Build WebGL
        uses: game-ci/unity-builder@v3
        with:
          projectPath: .
          unityVersion: 2021.3.33f1
          targetPlatform: WebGL
          buildName: webgl
          buildPath: build
          buildMethod: WebGLBuild.Build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: webgl-build
          path: build/WebGL

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: webgl-build
          path: webgl-build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: webgl-build

      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
